/*
 * Copyright (C) 2009 Samsung Electronics
 * Kyungmin Park <kyungmin.park@samsung.com>
 * Minkyu Kang <mk7.kang@samsung.com>
 *
 * SPDX-License-Identifier:	GPL-2.0+
 */

#include <config.h>
#include <asm/arch/cpu.h>
#include <asm/arch/power.h>

/*
 * Register usages:
 *
 * r5 has zero always
 */

	.globl lowlevel_init
lowlevel_init:
	mov	r9, lr

	#ifdef CONFIG_SPL_BUILD
	#if 0
	bl system_clock_init
	#else
	bl clock_init
	#endif
	bl sdram_init
	#else
	
	
	#endif


	mov	pc, r9			/* 返回 */